extends SceneTree

const EXPECTED := {
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_1_v1.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_2_v1.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_3_v1.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_1_v2.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_2_v2.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_3_v2.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_1_v1.png": Vector2i(1024, 384),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_2_v1.png": Vector2i(1024, 384),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_3_v1.png": Vector2i(1024, 384),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_1_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_2_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_3_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_1_body_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_1_basket_lowered_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_1_basket_raised_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_2_body_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_2_basket_lowered_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_2_basket_raised_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_3_body_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_3_basket_lowered_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_fryer_tier_3_basket_raised_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_auto_lift_arm_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/youtiao_auto_load_feeder_five_area_v4.png": Vector2i(1024, 512),
	"res://resources/art/effects/youtiao/youtiao_sizzle_bubbles_five_area_v4.png": Vector2i(256, 256),
	"res://resources/art/effects/youtiao/youtiao_oil_drips_five_area_v4.png": Vector2i(256, 256),
	"res://resources/art/workstation/expansion/tools/single_press_spreader_v1.png": Vector2i(1024, 1024),
	"res://resources/art/workstation/expansion/tools/automatic_sauce_brush_v1.png": Vector2i(1024, 1024),
	"res://resources/art/workstation/expansion/trays/ingredient_tray_4x3_v1.png": Vector2i(512, 240),
	"res://resources/art/workstation/expansion/trays/ingredient_slot_locked_cover_v1.png": Vector2i(512, 512),
	"res://resources/art/workstation/expansion/bins/small_ingredient_box_tier_1_v1.png": Vector2i(512, 512),
	"res://resources/art/workstation/expansion/bins/small_ingredient_box_tier_2_v1.png": Vector2i(512, 512),
	"res://resources/art/workstation/expansion/bins/small_ingredient_box_tier_3_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/soybean/yellow_soybean_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/beans/red_bean_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/beans/black_bean_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/plain_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/red_bean_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/black_bean_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/plain_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/sesame_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/scallion_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/plain_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/sesame_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/scallion_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/nuts/peanut_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/beans/mung_bean_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/grains/five_grain_mix_portion_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/peanut_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/mung_bean_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/products/soy_milk/five_grain_soy_milk_cup_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/glutinous_rice_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/multigrain_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/ingredients/youtiao/filled_youtiao_dough_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/glutinous_rice_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/multigrain_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/products/youtiao/filled_youtiao_v1.png": Vector2i(512, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_auto_cup_rack_empty_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_1_body_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_1_lid_closed_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_1_lid_open_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_2_body_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_2_lid_closed_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_2_lid_open_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_3_body_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_3_lid_closed_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/soy_milk_machine_tier_3_lid_open_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_1_base_body_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_1_basket_layer_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_1_lid_closed_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_1_lid_open_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_2_base_body_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_2_basket_layer_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_2_lid_closed_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_2_lid_open_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_3_base_body_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_3_basket_layer_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_3_lid_closed_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/workstation/expansion/machines/steamer_tier_3_lid_open_five_area_v3.png": Vector2i(1024, 512),
	"res://resources/art/products/soy_milk/soy_milk_cup_black_bean_v3.png": Vector2i(256, 256),
	"res://resources/art/products/soy_milk/soy_milk_cup_empty_v3.png": Vector2i(256, 256),
	"res://resources/art/products/soy_milk/soy_milk_cup_multigrain_v3.png": Vector2i(256, 256),
	"res://resources/art/products/soy_milk/soy_milk_cup_red_bean_v3.png": Vector2i(256, 256),
	"res://resources/art/products/soy_milk/soy_milk_cup_yellow_bean_v3.png": Vector2i(256, 256),
	"res://resources/art/effects/soy_milk/soy_milk_liquid_stream_v3.png": Vector2i(256, 256),
	"res://resources/art/effects/soy_milk/soy_milk_spoiled_vapor_v3.png": Vector2i(256, 256),
	"res://resources/art/effects/soy_milk/soy_milk_water_pour_v3.png": Vector2i(256, 256),
}


func _initialize() -> void:
	for path: String in EXPECTED:
		var texture := load(path) as Texture2D
		if texture == null:
			push_error("WORKSTATION EXPANSION ASSET SELF-CHECK FAIL: cannot load %s" % path)
			quit(1)
			return
		if texture.get_size() != Vector2(EXPECTED[path]):
			push_error("WORKSTATION EXPANSION ASSET SELF-CHECK FAIL: %s size %s expected %s" % [path, texture.get_size(), EXPECTED[path]])
			quit(1)
			return
	print("WORKSTATION EXPANSION ASSET SELF-CHECK PASS: %d textures" % EXPECTED.size())
	quit(0)
